### ISSUE TITLE
File Already Exists

### ISSUE THREAD

**Issue by wuseal** [wuseal/JsonToKotlinClass#123]
PluginVersion:3.0.1
User Config:
```json
{
  "uuid": "a1b5882e-ec6d-4567-823e-5e0cf5505958",
  "pluginVersion": "3.0.1",
  "isPropertiesVar": false,
  "isCommentOff": true,
  "isOrderByAlphabetical": true,
  "propertyTypeStrategy": "AutoDeterMineNullableOrNot",
  "initWithDefaultValue": false,
  "targetJsonConverterLib": "Gson",
  "isInnerClassMode": false,
  "customAnnotationImportClassString": "import kotlinx.serialization.SerialName\nimport kotlinx.serialization.Serializable\nimport kotlinx.serialization.Optional",
  "customClassAnnotationFormatString": "@Serializable",
  "customPropertyAnnotationFormatString": "@Optional\n@SerialName(\"%s\")",
  "enableMapType": false,
  "enableAutoReformat": true,
  "enableMinimalAnnotation": false,
  "parenClassTemplate": "",
  "keywordPropertyValid": true,
  "extensionsConfig": "",
  "timeStamp": "1553474343902",
  "daytime": "2019-03-24"
}
```

```
com.intellij.util.IncorrectOperationException: Cannot create file 'C:\src\training-master\app\src\main\java\com\example\post_sample\Model\user.kt'. File already exists.
	at com.intellij.psi.impl.file.PsiDirectoryImpl.checkName(PsiDirectoryImpl.java:465)
	at com.intellij.psi.impl.file.PsiDirectoryImpl.checkAdd(PsiDirectoryImpl.java:454)
	at com.intellij.psi.impl.file.PsiJavaDirectoryImpl.checkAdd(PsiJavaDirectoryImpl.java:80)
	at com.intellij.psi.impl.file.PsiDirectoryImpl.add(PsiDirectoryImpl.java:393)
	at com.intellij.psi.impl.file.PsiJavaDirectoryImpl.add(PsiJavaDirectoryImpl.java:65)
	at wu.seal.jsontokotlin.utils.KotlinDataClassFileGenerator$generateKotlinDataClassFile$1.invoke(KotlinDataClassFileGenerator.kt:234)
	at wu.seal.jsontokotlin.utils.KotlinDataClassFileGenerator$generateKotlinDataClassFile$1.invoke(KotlinDataClassFileGenerator.kt:21)
	at wu.seal.jsontokotlin.utils.SimplifiedMethodsKt$executeCouldRollBackAction$1$1.run(SimplifiedMethods.kt:26)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1038)
	at wu.seal.jsontokotlin.utils.SimplifiedMethodsKt$executeCouldRollBackAction$1.run(SimplifiedMethods.kt:25)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:139)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:97)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:87)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:73)
	at wu.seal.jsontokotlin.utils.SimplifiedMethodsKt.executeCouldRollBackAction(SimplifiedMethods.kt:24)
	at wu.seal.jsontokotlin.utils.KotlinDataClassFileGenerator.generateKotlinDataClassFile(KotlinDataClassFileGenerator.kt:231)
	at wu.seal.jsontokotlin.utils.KotlinDataClassFileGenerator.generateMultipleDataClassFiles(KotlinDataClassFileGenerator.kt:66)
	at wu.seal.jsontokotlin.GenerateKotlinFileAction.doGenerateKotlinDataClassFileAction(GenerateKotlinFileAction.kt:101)
	at wu.seal.jsontokotlin.GenerateKotlinFileAction.actionPerformed(GenerateKotlinFileAction.kt:63)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:255)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:272)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$0(ActionMenuItem.java:304)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:307)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:106)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:294)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$0(ActionMenuItem.java:114)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransaction$1(TransactionGuardImpl.java:111)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:120)
	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:122)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:114)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:529)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:49)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:549)
	at java.awt.Component.processMouseEvent(Component.java:6548)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3325)
	at java.awt.Component.processEvent(Component.java:6313)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4903)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:817)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:754)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:394)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

Error Json String:
```json
{
    "user": {
        "id": 29,
        "google_id": null,
        "name": "snoop",
        "email": "snoop@gmail.com",
        "image": null,
        "category_id": 1,
        "created_at": "2019-03-22 19:05:33",
        "updated_at": "2019-03-22 19:05:33"
    }
}
```

**Comment by wuseal** [comment]
How to trigger it：
First, create a new file named `user.kt`
Then use this plugin to do `generate kotlin data class from json` Action with root class name: `User`
Click `generate` and then this error will happen

**Comment by wuseal** [comment]
And this JSON with root class name : `BetSet` will also happen this error
```JS
{
	"error_state": {
		"code": 200,
		"description": "SUCCESS"
	},
	"results": {
		"predictions": [{
			"type": "simple",
			"sport": "soccer",
			"risk": "safe",
			"isFree": true,
			"betsets": [{
				"bets": [{
					"type": "home",
					"odds": [{
						"label": "H",
						"value": 1.34,
						"isSuggested": true,
						"bookmaker": "betclic"
					}, {
						"label": "H",
						"value": 1.34,
						"isSuggested": false,
						"bookmaker": "betclic"
					}, {
						"label": "H",
						"value": 1.34,
						"isSuggested": false,
						"bookmaker": "betclic"
					}],
					"homeTeam": "PSG",
					"awayTeam": "OM",
					"league": "Ligue 1",
					"game_date": "2019-01-01 14h"
				}],
				"probability": 75,
				"totalOdd": 1.34
			}]
		}, {
			"type": "combine",
			"sport": "soccer",
			"risk": "safe",
			"isFree": false,
			"betsets": [{
				"bets": [{
					"type": "home",
					"odds": [{
						"label": "H",
						"value": 1.21,
						"isSuggested": false,
						"bookmaker": "betclic"
					}, {
						"label": "H",
						"value": 2.34,
						"isSuggested": true,
						"bookmaker": "betclic"
					}, {
						"label": "H",
						"value": 3.42,
						"isSuggested": false,
						"bookmaker": "betclic"
					}],
					"homeTeam": "Manchester City",
					"awayTeam": "Arsenal",
					"league": "Ligue 1",
					"game_date": "2019-01-01 14h"
				}, {
					"type": "home",
					"odds": [{
						"label": "H",
						"value": 1.14,
						"isSuggested": true,
						"bookmaker": "betclic"
					}, {
						"label": "H",
						"value": 3.45,
						"isSuggested": false,
						"bookmaker": "betclic"
					}, {
						"label": "H",
						"value": 6.5,
						"isSuggested": false,
						"bookmaker": "betclic"
					}],
					"homeTeam": "AS Roma",
					"awayTeam": "Palerme",
					"league": "Ligue 1",
					"game_date": "2019-01-01 14h"
				}],
				"probability": 60,
				"totalOdd": 2.67
			}]
		}, {
			"type": "multiple",
			"sport": "soccer",
			"risk": "risky",
			"isFree": false,
			"betsets": [{
				"bets": [{
					"type": "home",
					"odds": [{
						"label": "H",
						"value": 1.34,
						"isSuggested": true,
						"bookmaker": "betclic"
					}, {
						"label": "H",
						"value": 1.34,
						"isSuggested": false,
						"bookmaker": "betclic"
					}, {
						"label": "H",
						"value": 1.34,
						"isSuggested": false,
						"bookmaker": "betclic"
					}],
					"homeTeam": "PSG",
					"awayTeam": "OM",
					"league": "Ligue 1",
					"game_date": "2019-01-01 14h"
				}],
				"probability": 60,
				"totalOdd": 1.34
			}, {
				"bets": [{
					"type": "home",
					"odds": [{
						"label": "H",
						"value": 1.34,
						"isSuggested": true,
						"bookmaker": "betclic"
					}, {
						"label": "H",
						"value": 1.34,
						"isSuggested": false,
						"bookmaker": "betclic"
					}, {
						"label": "H",
						"value": 1.34,
						"isSuggested": false,
						"bookmaker": "betclic"
					}],
					"homeTeam": "PSG",
					"awayTeam": "OM",
					"league": "Ligue 1",
					"game_date": "2019-01-01 14h"
				}],
				"probability": 60,
				"totalOdd": 1.34
			}]
		}],
		"affiliates": [{
			"partner": "https:\/\/www.top10-sites-paris-sportifs.fr\/wp-content\/uploads\/betclic-tsps.png",
			"bonusAmount": 150,
			"message": "100\u20ac offerts que le pari soit gagnant ou perdant !",
			"link": "http:\/\/google.fr"
		}, {
			"partner": "https:\/\/www.top10-sites-paris-sportifs.fr\/wp-content\/uploads\/betclic-tsps.png",
			"bonusAmount": 150,
			"message": "Pariez sans risques",
			"link": "http:\/\/google.fr"
		}]
	}
}
```

**Comment by Karthik2007** [comment]
@wuseal  can I take up this one?

**Comment by wuseal** [comment]
@Karthik2007  Yeah, Of course! That's Great!

**Comment by Karthik2007** [comment]
While Looking into the issue, I ran into another bug. Please check.

**Wrongly referenced Renamed class** 

Steps:
innerclassmodel = false
use plugin to do `generate kotlin data class File from json` Action with root class name: `ff`

Json

```
{
  "user": {
    "id": 29,
    "google_id": null,
    "name": "snoop",
    "email": "snoop@gmail.com",
    "image": null,
    "category_id": 1,
    "created_at": "2019-03-22 19:05:33",
    "updated_at": "2019-03-22 19:05:33"
  },
  "owner": {
    "user": {
      "privilege": "owner"
    }
  }
}
```

Bug: **UserX** class is generated after renaming but it is not referenced in the Final class structure.

**Comment by kezhenxu94** [comment]
> While Looking into the issue, I ran into another bug. Please check.
> 
> **Wrongly referenced Renamed class**
> 
> Steps:
> innerclassmodel = false
> use plugin to do `generate kotlin data class File from json` Action with root class name: `ff`
> 
> Json
> 
> ```
> {
>   "user": {
>     "id": 29,
>     "google_id": null,
>     "name": "snoop",
>     "email": "snoop@gmail.com",
>     "image": null,
>     "category_id": 1,
>     "created_at": "2019-03-22 19:05:33",
>     "updated_at": "2019-03-22 19:05:33"
>   },
>   "owner": {
>     "user": {
>       "privilege": "owner"
>     }
>   }
> }
> ```
> Bug: **UserX** class is generated after renaming but it is not referenced in the Final class structure.

Thanks for reporting, I've created another issue to track this one, comment under #136 and if you're interested in it, feel free to leave a comment and work on it, thanks

**Comment by wuseal** [comment]
@Karthik2007 For this issue belonged to the plan miles `3.2.0` and it's due to this weekend, we hope this issue could be fixed ahead the end of this weekend, And if any problem, please contact us, Thanks. 
Also, If you would like to join us to be collaborator，Feel free to add my wechat account `sealkingking`, thanks.

**Comment by Karthik2007** [comment]
@wuseal Sure. Planning to close this by weekend. Will post an update by tomorrow.

**Comment by wuseal** [comment]
Fixed in version 3.2.0

**Comment by Karthik2007** [comment]
> @Karthik2007 For this issue belonged to the plan miles `3.2.0` and it's due by this weekend, we hope this issue could be fixed ahead the end of this weekend, And if any problem, please contact us, Thanks.
> Also, If you would like to join us to be collaborator，Feel free to add my wechat account `sealkingking`, thanks.



> @Karthik2007 For this issue belonged to the plan miles `3.2.0` and it's due by this weekend, we hope this issue could be fixed ahead the end of this weekend, And if any problem, please contact us, Thanks.
> Also, If you would like to join us to be collaborator，Feel free to add my wechat account `sealkingking`, thanks.

Hey. Thanks for the invitation. I would be happy to be there.

**Comment by wuseal** [comment]
@Karthik2007 
Please download `Wechat` APP and add my account to be friends, My account is: `sealkingking`, Then we could pull you into the group.

**Comment by wuseal** [comment]
@Karthik2007 Or you may Join us by slack 
https://join.slack.com/t/jsontokotlinclass/shared_invite/enQtNjMwMTc0MDk2OTY0LTliM2Y2NGRiNTY2NGFjOTcwMDk4Mzk5ODRlY2M3MjAzNTZhZTMyOTViZTQzNWEwZTM2NGQ3OWM4YThhY2FlN2E

**Comment by Karthik2007** [comment]
Thanks @wuseal for the invitation. Happy to be there. I have joined the slack channel.
