### ISSUE TITLE
String index out of range: 1

### ISSUE THREAD

**Issue by wuseal** [wuseal/JsonToKotlinClass#15]
```
String index out of range: 1
java.lang.StringIndexOutOfBoundsException: String index out of range: 1
	at java.lang.String.substring(String.java:1963)
	at wu.seal.jsontokotlin.codeelements.KPropertyName.toLowerCamelCase(KPropertyName.kt:94)
	at wu.seal.jsontokotlin.codeelements.KPropertyName.makeCamelCaseLegalName(KPropertyName.kt:71)
	at wu.seal.jsontokotlin.codeelements.KPropertyName.makePropertyName(KPropertyName.kt:51)
	at wu.seal.jsontokotlin.codeelements.KPropertyName.getName(KPropertyName.kt:39)
	at wu.seal.jsontokotlin.supporter.CustomJsonLibSupporter.getJsonLibSupportPropertyBlockString(CustomJsonLibSupporter.kt:32)
	at wu.seal.jsontokotlin.codeelements.KProperty.getPropertyStringBlock(KProperty.kt:54)
	at wu.seal.jsontokotlin.KotlinMaker.addProperty(KotlinMaker.kt:95)
	at wu.seal.jsontokotlin.KotlinMaker.appendCodeMember(KotlinMaker.kt:76)
	at wu.seal.jsontokotlin.KotlinMaker.makeKotlinData(KotlinMaker.kt:37)
	at wu.seal.jsontokotlin.MakeKotlinClassAction$actionPerformed$2.invoke(MakeKotlinClassAction.kt:73)
	at wu.seal.jsontokotlin.MakeKotlinClassAction$actionPerformed$2.invoke(MakeKotlinClassAction.kt:23)
	at wu.seal.jsontokotlin.MakeKotlinClassActionKt$executeCouldRollBackAction$1$1.run(MakeKotlinClassAction.kt:97)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1023)
	at wu.seal.jsontokotlin.MakeKotlinClassActionKt$executeCouldRollBackAction$1.run(MakeKotlinClassAction.kt:96)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:149)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:109)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
	at wu.seal.jsontokotlin.MakeKotlinClassActionKt.executeCouldRollBackAction(MakeKotlinClassAction.kt:95)
	at wu.seal.jsontokotlin.MakeKotlinClassAction.actionPerformed(MakeKotlinClassAction.kt:61)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:215)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:232)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:570)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$2(IdeKeyEventDispatcher.java:619)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:193)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:618)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:477)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:211)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:633)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by wuseal** [comment]
###[This bug has been fixed in release version 1.5.1](https://github.com/wuseal/JsonToKotlinClass/releases/tag/1.5.1)
