### ISSUE TITLE
NoSuchElementException: null

### ISSUE THREAD

**Issue by cgoodroe** [wuseal/JsonToKotlinClass#2]
I get this error every time, and I know the Json is valid. Following steps just like your example, please take a look.

Also, it looks like you're generating comments to the right of each field? Could you make this an option also?

Thank you for working on this! It could be super useful.
```
null
java.util.NoSuchElementException
	at java.util.ArrayList$Itr.next(ArrayList.java:854)
	at wu.seal.jsontokotlin.KotlinMaker.getArrayType(KotlinMaker.java:92)
	at wu.seal.jsontokotlin.KotlinMaker.appendJsonObject(KotlinMaker.java:66)
	at wu.seal.jsontokotlin.KotlinMaker.makeKotlinData(KotlinMaker.java:38)
	at wu.seal.jsontokotlin.KotlinMaker.getJsonObjectType(KotlinMaker.java:84)
	at wu.seal.jsontokotlin.KotlinMaker.appendJsonObject(KotlinMaker.java:72)
	at wu.seal.jsontokotlin.KotlinMaker.makeKotlinData(KotlinMaker.java:38)
	at wu.seal.jsontokotlin.MakeKotlinClassAction$3$1.run(MakeKotlinClassAction.java:143)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:898)
	at wu.seal.jsontokotlin.MakeKotlinClassAction$3.run(MakeKotlinClassAction.java:131)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:129)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:100)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:86)
	at wu.seal.jsontokotlin.MakeKotlinClassAction.actionPerformed(MakeKotlinClassAction.java:128)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:197)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:156)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:211)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep.performAction(PopupFactoryImpl.java:875)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep.lambda$onChosen$0(PopupFactoryImpl.java:863)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:199)
	at com.intellij.ui.popup.AbstractPopup.lambda$null$7(AbstractPopup.java:1390)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:795)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:631)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:387)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by cgoodroe** [comment]
Also, just saw this issue with a simpler Json input, it looks like you'll need to handle some cases in this way:
```
@SerializedName("Accept-Language")
val AcceptLanguage
```
![screen shot 2017-09-15 at 11 13 46 am](https://user-images.githubusercontent.com/1252910/30494915-314fbc7e-9a07-11e7-902c-dc027999f3cc.png)

**Comment by wuseal** [comment]
@cgoodroe   I'm glad to receive your questions and bug，  I'm going to fix these problems soon. I also plan to add Gson and Jackson to the options

**Comment by wuseal** [comment]
@cgoodroe Could you Paste the raw Json String that cause the first Error log?

**Comment by wuseal** [comment]
@cgoodroe I make the generate code like this ,Have a look at it if it is OK
data class FDS(
		@SerializedName("while") val whileX: List<While>, //
		@SerializedName("interface") val interfaceX: List<Interface>, //
		@SerializedName("when") val whenX: List<When> //
)

data class When(
        @SerializedName("first-=Name") val firstName: String, //Eric
        @SerializedName("lastName") val lastName: String, //Clapton
        @SerializedName("instrument") val instrument: String //guitar
)

**Comment by cgoodroe** [comment]
@wuseal it looks like that first error log comes from an empty array, like this:
```
{
	"emptyArray": []
}
```

**Comment by cgoodroe** [comment]
@wuseal your example looks good, but why do some have 'X' appended? like while = whileX ?

**Comment by wuseal** [comment]
@cgoodroe First.Yes,I also conclude that It is an empty array, And Now I have make it available with a Object default array type.
Second. Why I append 'X'?.because the word 'when' ,'while' and 'interface' are all hard keyword in kotlin grammar, So I append the character 'X' to make the property name availiable.
Last. The comment option is like what you want ,the example upon isn't with comment option off,just with a comment that is empty. If no other problem ,I  release a new version to fix the issues in this topic.

**Comment by wuseal** [comment]
@cgoodroe New version has been released ,Have a test if it works well ,If all works well ,then u can close this issue

**Comment by cgoodroe** [comment]
@wuseal Nice work! I'll continue using this and let you know if I see anything else, thank you.
