### ISSUE TITLE
name.first() went wrong in Property.getCode() 

### ISSUE THREAD

**Issue by TedZen** [wuseal/JsonToKotlinClass#218]
"java.util.NoSuchElementException: Char sequence is empty" occurs when generating code from {"":1}

some infos:
config:{
"pluginVersion": "3.4.0",
  "isPropertiesVar": false,
  "isCommentOff": true,
  "isOrderByAlphabetical": true,
  "propertyTypeStrategy": "NotNullable",
  "defaultValueStrategy": "None",
  "targetJsonConverterLib": "None",
  "isInnerClassMode": false,
  "customAnnotationImportClassString": "import kotlinx.serialization.SerialName\nimport kotlinx.serialization.Serializable\nimport kotlinx.serialization.Optional",
  "customClassAnnotationFormatString": "@Serializable",
  "customPropertyAnnotationFormatString": "@Optional\n@SerialName(\"%s\")",
  "enableMapType": false,
  "enableMinimalAnnotation": false,
  "parenClassTemplate": "",
  "keywordPropertyValid": true,
  "extensionsConfig": ""
}

log:
java.util.NoSuchElementException: Char sequence is empty.
	at kotlin.text.StringsKt___StringsKt.first(_Strings.kt:73)
	at wu.seal.jsontokotlin.classscodestruct.Property.getCode(Property.kt:34)
	at wu.seal.jsontokotlin.classscodestruct.KotlinDataClass.getCode(KotlinDataClass.kt:33)
	at wu.seal.jsontokotlin.classscodestruct.KotlinDataClass.getCode$default(KotlinDataClass.kt:18)
	at wu.seal.jsontokotlin.KotlinDataClassCodeMaker$makeKotlinDataClassCode$1.invoke(KotlinDataClassCodeMaker.kt:28)
	at wu.seal.jsontokotlin.KotlinDataClassCodeMaker$makeKotlinDataClassCode$1.invoke(KotlinDataClassCodeMaker.kt:6)
	at kotlin.text.StringsKt__StringBuilderKt.appendElement(StringBuilder.kt:58)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinTo(_Collections.kt:2274)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinToString(_Collections.kt:2291)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinToString$default(_Collections.kt:2290)
	at wu.seal.jsontokotlin.KotlinDataClassCodeMaker.makeKotlinDataClassCode(KotlinDataClassCodeMaker.kt:27)
	at wu.seal.jsontokotlin.KotlinDataClassCodeMaker.makeKotlinDataClassCode(KotlinDataClassCodeMaker.kt:12)
	at wu.seal.jsontokotlin.MakeKotlinClassAction.insertKotlinCode(MakeKotlinClassAction.kt:135)
	at wu.seal.jsontokotlin.MakeKotlinClassAction.actionPerformed(MakeKotlinClassAction.kt:74)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:258)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:275)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:618)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$2(IdeKeyEventDispatcher.java:667)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:195)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:666)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:519)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:474)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:211)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:679)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by TedZen** [comment]
will be solved in issue #219
