### ISSUE TITLE
PrefixSupport will go wrong if Property.name is empty

### ISSUE THREAD

**Issue by TedZen** [wuseal/JsonToKotlinClass#227]
java.util.NoSuchElementException: Char sequence is empty.
	at kotlin.text.StringsKt___StringsKt.first(_Strings.kt:60)
	at extensions.wu.seal.PropertyPrefixSupport.intercept(PropertyPrefixSupport.kt:59)

Maybe we shouldn't adding pre&suffix when Property.name is empty

**Comment by TedZen** [comment]
fixed
