### ISSUE TITLE
java.io.FileNotFoundException: /Users/apple/Library/Caches/.jsontokotlin/actionInfo/1572435095855 (No such file or directory)

### ISSUE THREAD

**Issue by wuseal** [wuseal/JsonToKotlinClass#246]
```
java.io.FileNotFoundException: /Users/apple/Library/Caches/.jsontokotlin/actionInfo/1572435095855 (No such file or directory)
    at java.io.FileInputStream.open0(Native Method)
    at java.io.FileInputStream.open(FileInputStream.java:195)
    at java.io.FileInputStream.<init>(FileInputStream.java:138)
    at kotlin.io.FilesKt__FileReadWriteKt.readBytes(FileReadWrite.kt:63)
    at kotlin.io.FilesKt__FileReadWriteKt.readText(FileReadWrite.kt:101)
    at kotlin.io.FilesKt__FileReadWriteKt.readText$default(FileReadWrite.kt:101)
    at wu.seal.jsontokotlin.feedback.PersistCache.readAllCachedActionInfo(PersistCache.kt:78)
    at wu.seal.jsontokotlin.feedback.NetWorkKt$sendHistoryActionInfo$1.run(NetWork.kt:43)
    at java.lang.Thread.run(Thread.java:748)
```

**Comment by wuseal** [comment]
Nothing can do.
