### ISSUE TITLE
Latest plugin (3.6.0) throws  IllegalArgument exception.

### ISSUE THREAD

**Issue by sureshg** [wuseal/JsonToKotlinClass#284]
```java
java.lang.IllegalArgumentException: No enum constant wu.seal.jsontokotlin.model.TargetJsonConverter.Serilizable
	at java.base/java.lang.Enum.valueOf(Enum.java:240)
	at wu.seal.jsontokotlin.model.TargetJsonConverter.valueOf(TargetJsonConverter.kt)
	at wu.seal.jsontokotlin.model.IConfigManager$DefaultImpls.getTargetJsonConverterLib(IConfigManager.kt:87)
	at wu.seal.jsontokotlin.model.ConfigManager.getTargetJsonConverterLib(ConfigManager.kt:10)
	at wu.seal.jsontokotlin.feedback.ConfigInfo.<init>(Datas.kt:20)
	at wu.seal.jsontokotlin.feedback.ExceptionHandlerKt.getConfigInfo(ExceptionHandler.kt:56)
	at wu.seal.jsontokotlin.feedback.NetWorkKt.sendConfigInfo(NetWork.kt:28)
	at wu.seal.jsontokotlin.JsonToKotlinApplication$runActivity$1.run(JsonToKotlinApplication.kt:25)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by wuseal** [comment]
@sureshg Will look into it🧐

**Comment by wuseal** [comment]
@sureshg  Sorry to notify you that there is a setting key has been changed to a new key:
`Serilizable ` has been renamed to `Serializable` and then the bug happens, you need to reinstall the plugin, then this crash will not happen anymore.

**Comment by fcolasuonno** [comment]
It might be necessary to remove the line `<property name="target_json_converter_lib_key" value="Serilizable" />` from `~/Library/Preferences/<Idea product>/options/other.xml` (on mac, other location on windows/linux)

**Comment by sureshg** [comment]
Thanks. All those workarounds mentioned above, but still getting the same error.

**Comment by wuseal** [comment]
then try to reinstall the IDE:joy:

**Comment by wuseal** [comment]
I will release a bugfix version for this, Sorry for the inconvenient using experience

**Comment by wuseal** [comment]
New Release 3.6.1 had been published with fixed this bug
