### ISSUE TITLE
Crash when trying with SARIF JSON schema

### ISSUE THREAD

**Issue by chao2zhang** [wuseal/JsonToKotlinClass#333]
## Input
https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json

## Stacktrace
java.lang.StackOverflowError
	at kotlin.text.StringsKt__StringsKt.split$StringsKt__StringsKt(Strings.kt:1247)
	at kotlin.text.StringsKt__StringsKt.split(Strings.kt:1229)
	at kotlin.text.StringsKt__StringsKt.split$default(Strings.kt:1227)
	at wu.seal.jsontokotlin.model.jsonschema.JsonSchema.resolveDefinition(JsonSchema.kt:17)
	at wu.seal.jsontokotlin.utils.classgenerator.DataClassGeneratorByJSONSchema.getRealDefinition(DataClassGeneratorByJSONSchema.kt:104)

**Comment by wuseal** [comment]
@TedZen  PLS have a look at it
