### ISSUE TITLE
java.lang.IndexOutOfBoundsException: Collection doesn't contain element at index 31.

### ISSUE THREAD

**Issue by wuseal** [wuseal/JsonToKotlinClass#35]
PluginVersion 2.0
Exception Log：
```
java.lang.IndexOutOfBoundsException: Collection doesn't contain element at index 31.
	at kotlin.collections.CollectionsKt___CollectionsKt$elementAt$1.invoke(_Collections.kt:69)
	at kotlin.collections.CollectionsKt___CollectionsKt$elementAt$1.invoke(_Collections.kt)
	at kotlin.collections.CollectionsKt___CollectionsKt.elementAtOrElse(_Collections.kt:95)
	at kotlin.collections.CollectionsKt___CollectionsKt.elementAt(_Collections.kt:69)
	at wu.seal.jsontokotlin.KotlinCodeMaker.appendCodeMember(KotlinCodeMaker.kt:98)
	at wu.seal.jsontokotlin.KotlinCodeMaker.makeKotlinData(KotlinCodeMaker.kt:40)
	at wu.seal.jsontokotlin.MakeKotlinClassAction$insertKotlinCode$1.invoke(MakeKotlinClassAction.kt:124)
	at wu.seal.jsontokotlin.MakeKotlinClassAction$insertKotlinCode$1.invoke(MakeKotlinClassAction.kt:24)
	at wu.seal.jsontokotlin.utils.SimplifiedMethodsKt$executeCouldRollBackAction$1$1.run(SimplifiedMethods.kt:20)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1010)
	at wu.seal.jsontokotlin.utils.SimplifiedMethodsKt$executeCouldRollBackAction$1.run(SimplifiedMethods.kt:19)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:137)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:95)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:71)
	at wu.seal.jsontokotlin.utils.SimplifiedMethodsKt.executeCouldRollBackAction(SimplifiedMethods.kt:18)
	at wu.seal.jsontokotlin.MakeKotlinClassAction.insertKotlinCode(MakeKotlinClassAction.kt:112)
	at wu.seal.jsontokotlin.MakeKotlinClassAction.actionPerformed(MakeKotlinClassAction.kt:67)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:220)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:237)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:576)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$2(IdeKeyEventDispatcher.java:625)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:195)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:624)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:479)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:213)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:695)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:395)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by kezhenxu94** [comment]
Any test case?

**Comment by wuseal** [comment]
no, dosen't find reproduce case right now

**Comment by wuseal** [comment]
These error logs collected from the server.
