### ISSUE TITLE
Crash Report : java.lang.IndexOutOfBoundsException: Empty list doesn't contain element at index 0.

### ISSUE THREAD

**Issue by wuseal** [wuseal/JsonToKotlinClass#353]
```
java.lang.IndexOutOfBoundsException: Empty list doesn't contain element at index 0.
	at kotlin.collections.EmptyList.get(Collections.kt:36)
	at kotlin.collections.EmptyList.get(Collections.kt:24)
	at wu.seal.jsontokotlin.model.classscodestruct.ListClass.replaceReferencedClasses(ListClass.kt:25)
	at wu.seal.jsontokotlin.model.classscodestruct.ListClass.replaceReferencedClasses(ListClass.kt:11)
	at wu.seal.jsontokotlin.model.classscodestruct.KotlinClass$DefaultImpls.resolveNameConflicts(KotlinClass.kt:64)
	at wu.seal.jsontokotlin.model.classscodestruct.GenericKotlinClass$DefaultImpls.resolveNameConflicts(GenericKotlinClass.kt)
	at wu.seal.jsontokotlin.model.classscodestruct.UnModifiableGenericClass.resolveNameConflicts(UnModifiableGenericClass.kt:9)
	at wu.seal.jsontokotlin.model.classscodestruct.KotlinClass$DefaultImpls.resolveNameConflicts(KotlinClass.kt:63)
	at wu.seal.jsontokotlin.model.classscodestruct.GenericKotlinClass$DefaultImpls.resolveNameConflicts(GenericKotlinClass.kt)
	at wu.seal.jsontokotlin.model.classscodestruct.UnModifiableGenericClass.resolveNameConflicts(UnModifiableGenericClass.kt:9)
	at wu.seal.jsontokotlin.utils.KotlinClassFileGenerator.generateMultipleKotlinClassFiles(KotlinClassFileGenerator.kt:45)
	at wu.seal.jsontokotlin.GenerateKotlinFileAction.doGenerateKotlinDataClassFileAction(GenerateKotlinFileAction.kt:100)
	at wu.seal.jsontokotlin.GenerateKotlinFileAction.actionPerformed(GenerateKotlinFileAction.kt:60)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:282)
	a
```

Caused by: 
```json
[[""]]
```
With Configs:
```
  "isPropertiesVar": false,
  "isCommentOff": true,
  "isOrderByAlphabetical": true,
  "propertyTypeStrategy": "NotNullable",
  "defaultValueStrategy": "None",
  "targetJsonConverterLib": "None",
  "isInnerClassMode": false,
 "enableMapType": false,
  "enableMinimalAnnotation": false,
  "parenClassTemplate": "",
```

**Comment by wuseal** [comment]
Fixed in 3.7.1
