### ISSUE TITLE
Crash Report: java.lang.IllegalStateException: properties used kotlin classes size should be equal referenced classes size!

### ISSUE THREAD

**Issue by wuseal** [wuseal/JsonToKotlinClass#354]
```
java.lang.IllegalStateException: properties used kotlin classes size should be equal referenced classes size!
	at wu.seal.jsontokotlin.model.classscodestruct.DataClass.replaceReferencedClasses(DataClass.kt:38)
	at wu.seal.jsontokotlin.model.classscodestruct.KotlinClass$DefaultImpls.resolveNameConflicts(KotlinClass.kt:64)
	at wu.seal.jsontokotlin.model.classscodestruct.ModifiableKotlinClass$DefaultImpls.resolveNameConflicts(ModifiableKotlinClass.kt)
	at wu.seal.jsontokotlin.model.classscodestruct.DataClass.resolveNameConflicts(DataClass.kt:6)
	at wu.seal.jsontokotlin.model.classscodestruct.KotlinClass$DefaultImpls.resolveNameConflicts$default(KotlinClass.kt:57)
	at wu.seal.jsontokotlin.utils.KotlinClassCodeMaker.makeKotlinClassCode(KotlinClassCodeMaker.kt:21)
	at wu.seal.jsontokotlin.utils.KotlinClassCodeMaker.makeKotlinClassCode(KotlinClassCodeMaker.kt:12)
	at wu.seal.jsontokotlin.InsertKotlinClassAction.insertKotlinCode(InsertKotlinClassAction.kt:135)
	at wu.seal.jsontokotlin.InsertKotlinClassAction.actionPerformed(InsertKotlinClassAction.kt:74)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:280)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:274)
	at com.intellij.ui.popup.ActionPopupStep.performAction(ActionPopupStep.java:223)
	at com.intellij.ui.popup.ActionPopupStep.performAction(ActionPopupStep.java:213)
	at com.intellij.ui.popup.ActionPopupStep.lambda$onChosen$2(ActionPopupStep.java:207)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
```

Caused by:
```json
{
  "objList": [
    {
      "a": 1
    }
  ],
  "obj": {
    "a": 1
  }
}
```

With config:
```json
{
  "pluginVersion": "3.6.1",
  "isPropertiesVar": false,
  "isCommentOff": true,
  "isOrderByAlphabetical": true,
  "propertyTypeStrategy": "NotNullable",
  "defaultValueStrategy": "None",
  "targetJsonConverterLib": "None",
  "isInnerClassMode": false,
  "enableMapType": false,
  "enableMinimalAnnotation": false,
  "parenClassTemplate": "",
  "extensionsConfig": ""
}
```

**Comment by wuseal** [comment]
Fixed in 3.7.1
