### ISSUE TITLE
Attempt to modify read-only document

### ISSUE THREAD

**Issue by wuseal** [wuseal/JsonToKotlinClass#36]
PluginVersion 1.7.3
Exception Log:
```
com.intellij.openapi.editor.ReadOnlyModificationException: Attempt to modify read-only document
	at com.intellij.openapi.editor.impl.DocumentImpl.insertString(DocumentImpl.java:460)
	at wu.seal.jsontokotlin.MakeKotlinClassAction$insertKotlinCode$1.invoke(MakeKotlinClassAction.kt:135)
	at wu.seal.jsontokotlin.MakeKotlinClassAction$insertKotlinCode$1.invoke(MakeKotlinClassAction.kt:24)
	at wu.seal.jsontokotlin.utils.SimplifiedMethodsKt$executeCouldRollBackAction$1$1.run(SimplifiedMethods.kt:19)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1003)
	at wu.seal.jsontokotlin.utils.SimplifiedMethodsKt$executeCouldRollBackAction$1.run(SimplifiedMethods.kt:18)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.a(CoreCommandProcessor.java:149)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:109)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
	at wu.seal.jsontokotlin.utils.SimplifiedMethodsKt.executeCouldRollBackAction(SimplifiedMethods.kt:17)
	at wu.seal.jsontokotlin.MakeKotlinClassAction.insertKotlinCode(MakeKotlinClassAction.kt:123)
	at wu.seal.jsontokotlin.MakeKotlinClassAction.actionPerformed(MakeKotlinClassAction.kt:67)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:220)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:237)
	at com.intellij.ide.actions.GotoActionAction.a(GotoActionAction.java:332)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:111)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:120)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:271)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:424)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.k(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:650)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by bodiam** [comment]
I think I had a similar issue as this in my own plugin. I fixed it here, with help of Dimitry Jemerov:

https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/f4c7ee919ac7a17de33ff4314d246b55dd13036a/src/main/java/org/asciidoc/intellij/actions/asciidoc/CreateTableAction.java#L41

Hope that helps!
